#!/usr/bin/env bash
# Quick reference guide for Telegram Export Parser

echo "🚀 Telegram Export Parser - Quick Reference"
echo "============================================"
echo ""

# Display current structure
echo "📁 Project Structure:"
echo "├── Core Modules"
echo "│  ├── app.py          (Main CLI application)"
echo "│  ├── utils.py        (Helper functions)"
echo "│  ├── stats.py        (Statistical analysis)"
echo "│  ├── filters.py      (Message filtering)"
echo "│  ├── exporters.py    (Multi-format export)"
echo "│  └── config.py       (Configuration)"
echo "│"
echo "├── Interfaces"
echo "│  ├── web_ui.py       (Flask web interface)"
echo "│  └── examples.py     (Example scripts)"
echo "│"
echo "├── Resources"
echo "│  ├── templates/      (Web UI templates)"
echo "│  ├── telegram_output/ (Default output)"
echo "│  └── test_data.json  (Test dataset)"
echo "│"
echo "└── Documentation"
echo "   ├── README.md       (Project overview)"
echo "   ├── GUIDE.md        (Usage guide)"
echo "   └── CHANGES.md      (What's new)"
echo ""

echo "🎯 Command Reference:"
echo "===================="
echo ""

echo "1️⃣  Basic Usage"
echo "   python app.py -i result.json                # Interactive mode"
echo "   python app.py -i result.json -c \"Chat Name\"  # Export specific chat"
echo ""

echo "2️⃣  Export Formats"
echo "   --format txt   # Plain text (default)"
echo "   --format csv   # Spreadsheet format"
echo "   --format json  # Structured data"
echo "   --format html  # Web viewable"
echo "   --format md    # Markdown"
echo "   --format xlsx  # Excel workbook"
echo ""

echo "3️⃣  Advanced Options"
echo "   --all-chats    # Export all chats"
echo "   --stats        # Show statistics"
echo "   --stats-only   # Only show stats"
echo "   -o DIR         # Output directory"
echo ""

echo "4️⃣  Complete Examples"
echo "   python app.py -i data.json --all-chats --format xlsx"
echo "   python app.py -i data.json --stats-only"
echo "   python app.py -i data.json -c \"دوستان\" --format html --stats"
echo ""

echo "5️⃣  Web Interface"
echo "   pip install flask"
echo "   python web_ui.py"
echo "   # Open: http://localhost:5000"
echo ""

echo "6️⃣  Run Examples"
echo "   python examples.py"
echo ""

echo "7️⃣  Programming Mode"
echo "   python -c \"from filters import *; from exporters import *; ...\""
echo ""

echo "📊 Export Format Comparison:"
echo "============================"
echo ""
echo "Format  | Best For          | Size  | Features"
echo "--------|-------------------|-------|------------------------"
echo "TXT     | Quick preview     | Small | Human-readable"
echo "CSV     | Excel/Sheets      | Small | Tabular"
echo "JSON    | API/Processing    | Med   | Structured"
echo "HTML    | Web viewing       | Med   | Styled"
echo "MD      | Documentation     | Small | Git-friendly"
echo "XLSX    | Excel reports     | Med   | Formatting/Charts"
echo ""

echo "🔧 Installation & Setup:"
echo "========================"
echo ""
echo "# Install core dependencies"
echo "pip install -r requirements.txt"
echo ""
echo "# Optional: Web UI"
echo "pip install flask"
echo ""
echo "# Optional: Excel support"
echo "pip install openpyxl"
echo ""

echo "💡 Tips & Tricks:"
echo "================="
echo ""
echo "• Use --all-chats for faster batch processing"
echo "• Filter data programmatically for custom workflows"
echo "• Check examples.py for advanced usage patterns"
echo "• Use config.json to save default settings"
echo "• Large files? ijson auto-activates for streaming"
echo ""

echo "📚 Documentation:"
echo "================="
echo ""
echo "README.md   - Project overview & features"
echo "GUIDE.md    - Complete usage guide"
echo "CHANGES.md  - Version history & comparisons"
echo "examples.py - Real-world usage examples"
echo ""

echo "✅ All systems ready!"
