#!/usr/bin/env bash
# 🚀 Telegram Export Parser - Quick Start Guide
# This script provides quick reference for running the project locally

set -e

echo "🚀 Telegram Export Parser - Quick Start"
echo "========================================"
echo ""

# Check for docker-compose
if command -v docker-compose &> /dev/null; then
    echo "✅ Docker Compose found: $(docker-compose --version)"
    echo ""
    echo "To start all services (Frontend + Backend):"
    echo ""
    echo "  docker-compose up --build"
    echo ""
    echo "Services will be available at:"
    echo "  • Frontend:  http://localhost:3000"
    echo "  • Backend:   http://localhost:8000"
    echo "  • API Docs:  http://localhost:8000/docs"
    echo ""
    echo "To stop services:"
    echo "  docker-compose down"
    echo ""
else
    echo "⚠️  Docker Compose not found. Install it to use the quick start."
    echo ""
fi

echo "---"
echo "Manual Setup (without Docker):"
echo "=============================="
echo ""

echo "1️⃣  Backend (Python + FastAPI)"
echo ""
echo "  cd backend"
echo "  python -m venv venv"
echo "  source venv/bin/activate  # On Windows: venv\\Scripts\\activate"
echo "  pip install -r requirements.txt"
echo "  uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"
echo ""
echo "  Backend will run at: http://localhost:8000"
echo "  API Docs at:        http://localhost:8000/docs"
echo ""

echo "2️⃣  Frontend (Next.js + React)"
echo ""
echo "  cd frontend"
echo "  npm install"
echo "  npm run dev"
echo ""
echo "  Frontend will run at: http://localhost:3000"
echo ""

echo "---"
echo "📋 Quick Commands Reference:"
echo "==========================="
echo ""

echo "Backend Tests:"
echo "  cd backend && pytest"
echo ""

echo "Frontend Tests:"
echo "  cd frontend && npm run test"
echo ""

echo "Code Linting:"
echo "  Backend:  cd backend && pylint app/"
echo "  Frontend: cd frontend && npm run lint"
echo ""

echo "Code Formatting:"
echo "  Backend:  cd backend && black app/"
echo "  Frontend: cd frontend && npm run format"
echo ""

echo "Build for Production:"
echo "  Backend:  docker build -f backend/Dockerfile -t telegram-export-backend backend"
echo "  Frontend: cd frontend && npm run build && npm start"
echo ""

echo "---"
echo "🔍 Project Structure:"
echo "===================="
echo ""
echo "Telegram Export Parser/"
echo "├── frontend/          # Next.js frontend (Port 3000)"
echo "│   ├── pages/        # React pages"
echo "│   ├── components/   # React components"
echo "│   ├── styles/       # Tailwind CSS"
echo "│   └── package.json"
echo "│"
echo "├── backend/          # FastAPI backend (Port 8000)"
echo "│   ├── app/"
echo "│   │   ├── main.py  # Entry point"
echo "│   │   ├── routers/ # API routes"
echo "│   │   └── models/  # Data models"
echo "│   ├── tests/       # Test files"
echo "│   └── requirements.txt"
echo "│"
echo "├── docker-compose.yml # Local dev orchestration"
echo "├── README.md          # Project overview"
echo "├── GUIDE.md          # Developer guide"
echo "└── QUICKSTART.sh     # This file"
echo ""

echo "---"
echo "📚 Documentation:"
echo "================"
echo ""
echo "README.md   - Project overview, architecture, features"
echo "GUIDE.md    - Developer workflow, deployment, CI/CD"
echo "QUICKSTART.sh - This quick reference"
echo ""

echo "---"
echo "✅ All systems ready! Get started with:"
echo ""
echo "   docker-compose up"
echo ""
echo "or follow the manual setup steps above."
echo ""
